[repository]
name = "split-monitor-workspaces"
authors = ["rasaHosseinzadeh"]

[split-monitor-workspaces]
description = "Split monitor workspaces"
authors = ["rasaHosseinzadeh "]
output = "build/libsplit-monitor-workspaces.so"
build = [
    "meson setup build --wipe",
    "meson compile -C build",
]
